# Blog info
blog_name: Laomanco
slogan: 生命是一个长期而积累的过程 诸行无常 诸法无我 涅槃寂静 因缘和合而生 因缘散尽而灭
url: http://www.laomanco.com

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: Laomanco,建筑,设计,码农,足球,音乐,羽毛球

home_nav:
  - name: Life
    url: /archives
    target_blank: false #不在新页面打开
  - name: Tech
    url: /project/
    target_blank: true #在新页面打开
  - name: Me
    url: /about/
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false


page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: false # true|fase
  text: Test

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件 laomanco@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持forsigner
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png

post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showTocNumber: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST
highlight_theme: night

# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
hypercomments_id: 88547
# disqus_shortname: laomanco
# duoshuo_shortname: 
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "Laomanco"
    - "喜欢音乐，也爱好运动，用文字和图片记录生活的美"
    - "其实码字和码code是差不多的，只是encoding不一样"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@xiaolianghuang"
    text_value_url: https://github.com/forsigner
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@definifely"
    text_value_url: http://weibo.com/definifely
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "laomanco@gmail.com"
  - type: location
    icon: icon-location
    text_value: 上海

link:
  - name: 流年
    info: 落叶旋起的气息 迷失了整个黄昏风
    url: http://xiaoyingwenwen.blogbus.com/
    avatar: 

project:
  - type: personal
    name: fexo
    url: https://github.com/forsigner/fexo
    intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  - type: personal
    name: beside
    url: https://github.com/forsigner/beside
    intro: I need you beside me
  - type: personal
    name: web-fontmin
    url: https://github.com/forsigner/web-fontmin
    intro: 字体子集化，在线提取你需要的字体